# Generated by Django 4.2.4 on 2023-08-22 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BTC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('fiat', models.CharField(max_length=10)),
                ('crypto', models.DecimalField(decimal_places=10, max_digits=20)),
            ],
        ),
    ]
